#!/bin/bash
tvservice -p &&
#echo 0 > /sys/class/graphics/fb0/blank 
omxplayer --no-keys --avdict rtsp_transport:tcp "rtsp://admin:admin123@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0" &
sleep 60
killall omxplayer.bin
tvservice -o


